services:
  process_builder:
      class: Symfony\Component\Process\ProcessBuilder

  task_runner:
      class: QualityChecker\Task\TaskRunner

  phpcs:
    class: QualityChecker\Task\Phpcs
    arguments:
      - phpcs: "@=parameter('phpcs') ? parameter('phpcs') : []"
      - %bin_dir%
      - @process_builder
    tags:
      - {name: task}

  phpmd:
    class: QualityChecker\Task\Phpmd
    arguments:
      - phpmd: "@=parameter('phpmd') ? parameter('phpmd') : []"
      - %bin_dir%
      - @process_builder
    tags:
      - {name: task}

  logger_stream:
    class: Monolog\Handler\StreamHandler
    arguments:
      - %log_dir%%log_file%

  logger:
    class: Monolog\Logger
    arguments:
      - QUALITY-CHECKER
    calls:
      - [pushHandler, [@logger_stream]]
