services:
  task_runner:
      class: QualityChecker\Task\TaskRunner

  phpcs:
    class: QualityChecker\Task\Phpcs
    arguments:
      - "@=parameter('phpcs') ? parameter('phpcs') : []"
      - %bin_dir%
    tags:
      - {name: task}

  phpmd:
    class: QualityChecker\Task\Phpmd
    arguments:
      - "@=parameter('phpmd') ? parameter('phpmd') : []"
      - %bin_dir%
    tags:
      - {name: task}

  logger_stream:
    class: Monolog\Handler\StreamHandler
    arguments:
      - %log_dir%%log_file%

  logger:
    class: Monolog\Logger
    arguments:
      - QUALITY-CHECKER
    calls:
      - [pushHandler, [@logger_stream]]
